"""add variant answer model

Revision ID: 0a823171345e
Revises: f26b171d2da1
Create Date: 2024-04-09 02:28:50.857613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a823171345e'
down_revision = 'f26b171d2da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
