"""add variant answer model

Revision ID: 740a688d94fc
Revises: eda8a496666b
Create Date: 2024-04-09 02:19:57.220440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740a688d94fc'
down_revision = 'eda8a496666b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
