"""add variant answer model

Revision ID: 8dd762276cdb
Revises: cfa8c14ca6da
Create Date: 2024-04-09 02:18:43.308825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd762276cdb'
down_revision = 'cfa8c14ca6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
