"""add variant answer model

Revision ID: 953efede4100
Revises: 0a823171345e
Create Date: 2024-04-09 02:31:34.530518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953efede4100'
down_revision = '0a823171345e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
