"""add variant answer model

Revision ID: cfa8c14ca6da
Revises: 5164cfba140a
Create Date: 2024-04-09 02:17:38.266571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa8c14ca6da'
down_revision = '5164cfba140a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
