"""add variant answer model

Revision ID: eda8a496666b
Revises: 8dd762276cdb
Create Date: 2024-04-09 02:18:50.248870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda8a496666b'
down_revision = '8dd762276cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
