"""add variant answer model

Revision ID: f26b171d2da1
Revises: 740a688d94fc
Create Date: 2024-04-09 02:20:43.414090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26b171d2da1'
down_revision = '740a688d94fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
